In [9]:
import pandas as pd
import geopandas as gpd
import json
from shapely.geometry import shape
from shapely import wkt
import warnings
# filter all warnings
warnings.filterwarnings("ignore")

In [10]:
neigh = pd.read_csv("Data/Neigh/neigh.csv")

neigh["geometry"] = neigh["geom"].apply(wkt.loads)

neigh = gpd.GeoDataFrame(
    neigh,
    geometry="geometry",
    crs="EPSG:4326"
)
neigh = neigh[["name", "geometry"]]
neigh["geometry"] = neigh.buffer(0)

HE SUBtituit els punts de les parades de fcg.metro amb els punts de les dades de tmb

In [11]:
with open('data/FGC/fgc_stops.json') as f:
    data = json.load(f)
fgc_stops = []
for stop in data['features']:
    properties = stop.get('properties', {})
    stop_id = properties.get('stop_id')
    stop_name = properties.get('stop_name')

    
    fgc_stops.append({
        'stop_id': stop_id,
        'stop_name': stop_name,
        'geometry': shape(stop['geometry'])

    })  
geo_df_fgc_stops = gpd.GeoDataFrame(fgc_stops, crs="EPSG:4326")
geo_df_fgc_stops.to_crs(epsg=25831, inplace=True)
neigh = neigh.to_crs(epsg=25831)
geo_df_fgc_stops = geo_df_fgc_stops[
    geo_df_fgc_stops.within(
        neigh.geometry.buffer(2500).union_all()
    )
]

geo_df_fgc_stops.to_crs(epsg=4326, inplace=True)
neigh.to_crs(epsg=4326, inplace=True)
geo_df_fgc_stops.sort_values(by='stop_id',inplace=True)
geo_df_fgc_stops.drop_duplicates(subset=['stop_name'], inplace=True,keep='first')
geo_df_fgc_stops['stop_name'].replace({
    'Barcelona - Plaça Catalunya': 'Catalunya',
    "L'Hospitalet Av. Carrilet": "Av. Carrilet",
    'Provença': 'Diagonal',
    'Barcelona - Plaça Espanya': 'Espanya',
}, inplace=True)

geo_df_fgc_stops = geo_df_fgc_stops[~geo_df_fgc_stops['stop_name'].isin(['Vallvidrera Inferior','Vallvidrera Superior'])]
geo_df_fgc_stops

    stop_id                stop_name                  geometry
45       AL                   Almeda  POINT (2.08525 41.35307)
4        BN              La Bonanova  POINT (2.13643 41.39782)
11       EP                El Putxet  POINT (2.13915 41.40583)
240      EU            Europa | Fira   POINT (2.1242 41.35656)
149      GO                   Gornal  POINT (2.11743 41.35489)
203      GR                   Gràcia   POINT (2.15266 41.3991)
235      IC           Ildefons Cerdà  POINT (2.13002 41.36091)
18       LF              La Floresta  POINT (2.07317 41.44487)
152      LH             Av. Carrilet  POINT (2.10271 41.35793)
218      LP               Les Planes   POINT (2.09162 41.4274)
234      MG       Magòria La Campana  POINT (2.13888 41.36749)
3        MN                 Muntaner  POINT (2.14235 41.39853)
201      PC                Catalunya  POINT (2.16872 41.38563)
9        PD                    Pàdua  POINT (2.14276 41.40351)
143      PE                  Espanya  POINT (2.14846 41.37472)
13       PF        Peu del Funicular  POINT (2.11118 41.40922)
123      PM               Pl. Molina  POINT (2.14675 41.40169)
116      PR                 Diagonal  POINT (2.15803 41.39281)
212      RE           Reina Elisenda  POINT (2.11893 41.39875)
2        SG             Sant Gervasi  POINT (2.14713 41.40107)
151      SP               Sant Josep   POINT (2.10992 41.3607)
210      SR                   Sarrià   POINT (2.12557 41.3985)
126      TB             Av. Tibidabo  POINT (2.13716 41.40965)
121      TT          Les Tres Torres   POINT (2.13081 41.3978)
221      VD               Valldoreix  POINT (2.06831 41.45784)
217      VL  Baixador de Vallvidrera  POINT (2.09694 41.42009)

# Solutions

In [12]:
solutions = geo_df_fgc_stops.copy()
# already_in_metro = ['Catalunya', 'Diagonal', 'Espanya','Av. Carrilet','Europa | Fira']
# solutions = solutions[~solutions['stop_name'].isin(already_in_metro)]
solutions.insert(2, 'stop_type', 'FGC')
solutions.rename(columns={'stop_name': 'name'}, inplace=True)
solutions['id'] = 'SF' + '-' + solutions['stop_id'].astype(str)
solutions['linia'] = 'IU Stop'
solutions = solutions[['id', 'stop_id', 'name', 'linia', 'stop_type', 'geometry']]
solutions

,id,stop_id,name,linia,stop_type,geometry
45,SF-AL,AL,Almeda,IU Stop,FGC,POINT (2.08525 41.35307)
4,SF-BN,BN,La Bonanova,IU Stop,FGC,POINT (2.13643 41.39782)
11,SF-EP,EP,El Putxet,IU Stop,FGC,POINT (2.13915 41.40583)
240,SF-EU,EU,Europa | Fira,IU Stop,FGC,POINT (2.1242 41.35656)
149,SF-GO,GO,Gornal,IU Stop,FGC,POINT (2.11743 41.35489)
203,SF-GR,GR,Gràcia,IU Stop,FGC,POINT (2.15266 41.3991)
235,SF-IC,IC,Ildefons Cerdà,IU Stop,FGC,POINT (2.13002 41.36091)
18,SF-LF,LF,La Floresta,IU Stop,FGC,POINT (2.07317 41.44487)
152,SF-LH,LH,Av. Carrilet,IU Stop,FGC,POINT (2.10271 41.35793)
218,SF-LP,LP,Les Planes,IU Stop,FGC,POINT (2.09162 41.4274)
234,SF-MG,MG,Magòria La Campana,IU Stop,FGC,POINT (2.13888 41.36749)
3,SF-MN,MN,Muntaner,IU Stop,FGC,POINT (2.14235 41.39853)
201,SF-PC,PC,Catalunya,IU Stop,FGC,POINT (2.16872 41.38563)
9,SF-PD,PD,Pàdua,IU Stop,FGC,POINT (2.14276 41.40351)
143,SF-PE,PE,Espanya,IU Stop,FGC,POINT (2.14846 41.37472)
13,SF-PF,PF,Peu del Funicular,IU Stop,FGC,POINT (2.11118 41.40922)
123,SF-PM,PM,Pl. Molina,IU Stop,FGC,POINT (2.14675 41.40169)
116,SF-PR,PR,Diagonal,IU Stop,FGC,POINT (2.15803 41.39281)
212,SF-RE,RE,Reina Elisenda,IU Stop,FGC,POINT (2.11893 41.39875)
2,SF-SG,SG,Sant Gervasi,IU Stop,FGC,POINT (2.14713 41.40107)
151,SF-SP,SP,Sant Josep,IU Stop,FGC,POINT (2.10992 41.3607)
210,SF-SR,SR,Sarrià,IU Stop,FGC,POINT (2.12557 41.3985)
126,SF-TB,TB,Av. Tibidabo,IU Stop,FGC,POINT (2.13716 41.40965)
121,SF-TT,TT,Les Tres Torres,IU Stop,FGC,POINT (2.13081 41.3978)
221,SF-VD,VD,Valldoreix,IU Stop,FGC,POINT (2.06831 41.45784)
217,SF-VL,VL,Baixador de Vallvidrera,IU Stop,FGC,POINT (2.09694 41.42009)

In [13]:
solutions.to_csv('Nodes/FGC-Sol.csv', index=False)

# FGC

In [14]:
stops_map = {
    'Catalunya': ['L6', 'L7', 'S1'],
    'Diagonal': ['L6', 'L7', 'S1'],
    'Gràcia': ['L6', 'L7', 'S1'],
    'Sant Gervasi': ['L6', 'S1'],
    'Muntaner': ['L6', 'S1'],
    'La Bonanova': ['L6', 'S1'],
    'Les Tres Torres': ['L6', 'S1'],
    'Sarrià': ['L6', 'S1', 'L12'],
    'Pl. Molina': ['L7'],
    'Pàdua': ['L7'],
    'El Putxet': ['L7'],
    'Av. Tibidabo': ['L7'],
    'Espanya': ['L8'],
    'Magòria La Campana': ['L8'],
    'Ildefons Cerdà': ['L8'],
    'Europa | Fira': ['L8'],
    'Gornal': ['L8'],
    'Sant Josep': ['L8'],
    'Av. Carrilet': ['L8'],
    'Almeda': ['L8'],
    'Peu del Funicular': ['S1'],
    'Baixador de Vallvidrera': ['S1'],
    'Les Planes': ['S1'],
    'La Floresta': ['S1'],
    'Valldoreix': ['S1'],
    'Reina Elisenda': ['L12']
}

In [15]:
geo_df_fgc_stops['linia'] = geo_df_fgc_stops['stop_name'].map(stops_map)
geo_df_fgc_stops = geo_df_fgc_stops.explode('linia', ignore_index=True)
geo_df_fgc_stops.sort_values(by='stop_name',inplace=True)
geo_df_fgc_stops.rename(columns={'stop_name': 'name'}, inplace=True)
geo_df_fgc_stops['stop_type'] = 'FGC'
geo_df_fgc_stops['id'] = 'F' + '-' + geo_df_fgc_stops['linia'] + '-' + geo_df_fgc_stops['stop_id'].astype(str)
geo_df_fgc_stops = geo_df_fgc_stops[['id', 'stop_id', 'name', 'linia', 'stop_type', 'geometry']]
geo_df_fgc_stops

,id,stop_id,name,linia,stop_type,geometry
0,F-L8-AL,AL,Almeda,L8,FGC,POINT (2.08525 41.35307)
11,F-L8-LH,LH,Av. Carrilet,L8,FGC,POINT (2.10271 41.35793)
33,F-L7-TB,TB,Av. Tibidabo,L7,FGC,POINT (2.13716 41.40965)
37,F-S1-VL,VL,Baixador de Vallvidrera,S1,FGC,POINT (2.09694 41.42009)
18,F-S1-PC,PC,Catalunya,S1,FGC,POINT (2.16872 41.38563)
17,F-L7-PC,PC,Catalunya,L7,FGC,POINT (2.16872 41.38563)
16,F-L6-PC,PC,Catalunya,L6,FGC,POINT (2.16872 41.38563)
25,F-S1-PR,PR,Diagonal,S1,FGC,POINT (2.15803 41.39281)
24,F-L7-PR,PR,Diagonal,L7,FGC,POINT (2.15803 41.39281)
23,F-L6-PR,PR,Diagonal,L6,FGC,POINT (2.15803 41.39281)
3,F-L7-EP,EP,El Putxet,L7,FGC,POINT (2.13915 41.40583)
20,F-L8-PE,PE,Espanya,L8,FGC,POINT (2.14846 41.37472)
4,F-L8-EU,EU,Europa | Fira,L8,FGC,POINT (2.1242 41.35656)
5,F-L8-GO,GO,Gornal,L8,FGC,POINT (2.11743 41.35489)
7,F-L7-GR,GR,Gràcia,L7,FGC,POINT (2.15266 41.3991)
8,F-S1-GR,GR,Gràcia,S1,FGC,POINT (2.15266 41.3991)
6,F-L6-GR,GR,Gràcia,L6,FGC,POINT (2.15266 41.3991)
9,F-L8-IC,IC,Ildefons Cerdà,L8,FGC,POINT (2.13002 41.36091)
1,F-L6-BN,BN,La Bonanova,L6,FGC,POINT (2.13643 41.39782)
2,F-S1-BN,BN,La Bonanova,S1,FGC,POINT (2.13643 41.39782)
10,F-S1-LF,LF,La Floresta,S1,FGC,POINT (2.07317 41.44487)
12,F-S1-LP,LP,Les Planes,S1,FGC,POINT (2.09162 41.4274)
34,F-L6-TT,TT,Les Tres Torres,L6,FGC,POINT (2.13081 41.3978)
35,F-S1-TT,TT,Les Tres Torres,S1,FGC,POINT (2.13081 41.3978)
13,F-L8-MG,MG,Magòria La Campana,L8,FGC,POINT (2.13888 41.36749)
14,F-L6-MN,MN,Muntaner,L6,FGC,POINT (2.14235 41.39853)
15,F-S1-MN,MN,Muntaner,S1,FGC,POINT (2.14235 41.39853)
21,F-S1-PF,PF,Peu del Funicular,S1,FGC,POINT (2.11118 41.40922)
22,F-L7-PM,PM,Pl. Molina,L7,FGC,POINT (2.14675 41.40169)
19,F-L7-PD,PD,Pàdua,L7,FGC,POINT (2.14276 41.40351)
26,F-L12-RE,RE,Reina Elisenda,L12,FGC,POINT (2.11893 41.39875)
28,F-S1-SG,SG,Sant Gervasi,S1,FGC,POINT (2.14713 41.40107)
27,F-L6-SG,SG,Sant Gervasi,L6,FGC,POINT (2.14713 41.40107)
29,F-L8-SP,SP,Sant Josep,L8,FGC,POINT (2.10992 41.3607)
30,F-L6-SR,SR,Sarrià,L6,FGC,POINT (2.12557 41.3985)
31,F-S1-SR,SR,Sarrià,S1,FGC,POINT (2.12557 41.3985)
32,F-L12-SR,SR,Sarrià,L12,FGC,POINT (2.12557 41.3985)
36,F-S1-VD,VD,Valldoreix,S1,FGC,POINT (2.06831 41.45784)

In [16]:
geo_df_fgc_stops.to_csv('Nodes/FGC.csv', index=False)