In [28]:
import pandas as pd
import geopandas as gpd
from shapely import wkt

In [29]:
bus = pd.read_csv('Nodes/Bus.csv')
fgc = pd.read_csv('Nodes/FGC.csv')
metro = pd.read_csv('Nodes/Metro.csv')
tram = pd.read_csv('Nodes/Tram.csv')

all_stops = pd.concat([ bus, fgc, metro, tram], ignore_index=True)
all_stops['geometry']= all_stops['geometry'].apply(wkt.loads)
all_stops = gpd.GeoDataFrame(all_stops, geometry='geometry', crs="EPSG:4326")

exchange_edges = pd.read_csv('Edges/Exchanges.csv')
exchange_edges

,origen,dest,tram,mode,lines,type,time,directed,geometry
0,SB-2,B-59-2,Av Icària - Àlaba - Av Icària - Àlaba,Bus - Bus,IU Stop - 59,Exchange - Self,01:00,True,POINT (2.198984998801282 41.393104003754864)
1,B-H16-2,B-59-2,Av Icària - Àlaba - Av Icària - Àlaba,Bus - Bus,H16 - 59,Exchange - Self,01:00,True,POINT (2.198984998801282 41.393104003754864)
2,B-V27-2,B-59-2,Av Icària - Àlaba - Av Icària - Àlaba,Bus - Bus,V27 - 59,Exchange - Self,01:00,True,POINT (2.198984998801282 41.393104003754864)
3,SB-2,B-H16-2,Av Icària - Àlaba - Av Icària - Àlaba,Bus - Bus,IU Stop - H16,Exchange - Self,01:00,True,POINT (2.198984998801282 41.393104003754864)
4,B-59-2,B-H16-2,Av Icària - Àlaba - Av Icària - Àlaba,Bus - Bus,59 - H16,Exchange - Self,01:00,True,POINT (2.198984998801282 41.393104003754864)
...,...,...,...,...,...,...,...,...,...
138110,B-V33-3596,T-T6-MINA,La Mina - Ponent - La Mina,Bus - Tram,V33 - T6,Exchange,04:34,True,"LINESTRING (2.2172843 41.4188065, 2.2174015 41..."
138111,B-B23-105999,T-T6-MINA,Rambla de la Mina - La Mina,Bus - Tram,B23 - T6,Exchange,01:48,True,"LINESTRING (2.2224278 41.4182191, 2.222341 41...."
138112,B-B23-106000,T-T6-MINA,CAP La Mina - La Mina,Bus - Tram,B23 - T6,Exchange,04:10,True,"LINESTRING (2.2201838 41.4156256, 2.2204138 41..."
138113,T-T5-PARC,T-T6-MINA,Parc del Besòs - La Mina,Tram - Tram,T5 - T6,Exchange,04:51,True,"LINESTRING (2.2171297 41.4191608, 2.2171685 41..."
138114,T-T6-PARC,T-T6-MINA,Parc del Besòs - La Mina,Tram - Tram,T6 - T6,Exchange,04:51,True,"LINESTRING (2.2171297 41.4191608, 2.2171685 41..."

In [30]:
exchange_edges['mode'].value_counts()

mode
Bus - Bus        127624
Metro - Bus        4341
Tram - Bus         1684
Bus - Tram         1543
Bus - Metro        1103
FGC - Bus           727
Bus - FGC           607
Tram - Tram         177
Metro - Metro        91
Metro - FGC          81
FGC - FGC            71
Metro - Tram         47
Tram - Metro         14
FGC - Metro           5
Name: count, dtype: int64

In [31]:
exchange_edges = exchange_edges.merge(all_stops[['id','stop_id']], left_on='dest', right_on='id', how='left')
exchange_edges

,origen,dest,tram,mode,lines,type,time,directed,geometry,id,stop_id
0,SB-2,B-59-2,Av Icària - Àlaba - Av Icària - Àlaba,Bus - Bus,IU Stop - 59,Exchange - Self,01:00,True,POINT (2.198984998801282 41.393104003754864),B-59-2,2
1,B-H16-2,B-59-2,Av Icària - Àlaba - Av Icària - Àlaba,Bus - Bus,H16 - 59,Exchange - Self,01:00,True,POINT (2.198984998801282 41.393104003754864),B-59-2,2
2,B-V27-2,B-59-2,Av Icària - Àlaba - Av Icària - Àlaba,Bus - Bus,V27 - 59,Exchange - Self,01:00,True,POINT (2.198984998801282 41.393104003754864),B-59-2,2
3,SB-2,B-H16-2,Av Icària - Àlaba - Av Icària - Àlaba,Bus - Bus,IU Stop - H16,Exchange - Self,01:00,True,POINT (2.198984998801282 41.393104003754864),B-H16-2,2
4,B-59-2,B-H16-2,Av Icària - Àlaba - Av Icària - Àlaba,Bus - Bus,59 - H16,Exchange - Self,01:00,True,POINT (2.198984998801282 41.393104003754864),B-H16-2,2
...,...,...,...,...,...,...,...,...,...,...,...
138110,B-V33-3596,T-T6-MINA,La Mina - Ponent - La Mina,Bus - Tram,V33 - T6,Exchange,04:34,True,"LINESTRING (2.2172843 41.4188065, 2.2174015 41...",T-T6-MINA,MINA
138111,B-B23-105999,T-T6-MINA,Rambla de la Mina - La Mina,Bus - Tram,B23 - T6,Exchange,01:48,True,"LINESTRING (2.2224278 41.4182191, 2.222341 41....",T-T6-MINA,MINA
138112,B-B23-106000,T-T6-MINA,CAP La Mina - La Mina,Bus - Tram,B23 - T6,Exchange,04:10,True,"LINESTRING (2.2201838 41.4156256, 2.2204138 41...",T-T6-MINA,MINA
138113,T-T5-PARC,T-T6-MINA,Parc del Besòs - La Mina,Tram - Tram,T5 - T6,Exchange,04:51,True,"LINESTRING (2.2171297 41.4191608, 2.2171685 41...",T-T6-MINA,MINA
138114,T-T6-PARC,T-T6-MINA,Parc del Besòs - La Mina,Tram - Tram,T6 - T6,Exchange,04:51,True,"LINESTRING (2.2171297 41.4191608, 2.2171685 41...",T-T6-MINA,MINA

# Tram

In [32]:
exchange_edges_tram = exchange_edges[exchange_edges['dest'].str.startswith('T')]
exchange_edges_tram

,origen,dest,tram,mode,lines,type,time,directed,geometry,id,stop_id
11832,ST-FRMC,T-T1-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,IU Stop - T1,Exchange - Self,02:00,True,POINT (2.143174886703491 41.3922004699707),T-T1-FRMC,FRMC
11833,T-T2-FRMC,T-T1-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,T2 - T1,Exchange - Self,01:00,True,POINT (2.143174886703491 41.3922004699707),T-T1-FRMC,FRMC
11834,T-T3-FRMC,T-T1-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,T3 - T1,Exchange - Self,01:00,True,POINT (2.143174886703491 41.3922004699707),T-T1-FRMC,FRMC
11835,ST-FRMC,T-T2-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,IU Stop - T2,Exchange - Self,02:00,True,POINT (2.143174886703491 41.3922004699707),T-T2-FRMC,FRMC
11836,T-T1-FRMC,T-T2-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,T1 - T2,Exchange - Self,01:00,True,POINT (2.143174886703491 41.3922004699707),T-T2-FRMC,FRMC
...,...,...,...,...,...,...,...,...,...,...,...
138110,B-V33-3596,T-T6-MINA,La Mina - Ponent - La Mina,Bus - Tram,V33 - T6,Exchange,04:34,True,"LINESTRING (2.2172843 41.4188065, 2.2174015 41...",T-T6-MINA,MINA
138111,B-B23-105999,T-T6-MINA,Rambla de la Mina - La Mina,Bus - Tram,B23 - T6,Exchange,01:48,True,"LINESTRING (2.2224278 41.4182191, 2.222341 41....",T-T6-MINA,MINA
138112,B-B23-106000,T-T6-MINA,CAP La Mina - La Mina,Bus - Tram,B23 - T6,Exchange,04:10,True,"LINESTRING (2.2201838 41.4156256, 2.2204138 41...",T-T6-MINA,MINA
138113,T-T5-PARC,T-T6-MINA,Parc del Besòs - La Mina,Tram - Tram,T5 - T6,Exchange,04:51,True,"LINESTRING (2.2171297 41.4191608, 2.2171685 41...",T-T6-MINA,MINA
138114,T-T6-PARC,T-T6-MINA,Parc del Besòs - La Mina,Tram - Tram,T6 - T6,Exchange,04:51,True,"LINESTRING (2.2171297 41.4191608, 2.2171685 41...",T-T6-MINA,MINA

## TBX

In [33]:
stop_times_x = pd.read_table('Data/Tram/TBX/stop_times.txt', sep=',')
stop_times_S = pd.read_table('Data/Tram/TBS/stop_times.txt', sep=',')
stop_times = pd.concat([stop_times_x, stop_times_S])    
stop_times = stop_times[stop_times['departure_time'].notna()]
stop_times = stop_times[['trip_id','stop_id','departure_time']]
stop_times = stop_times[stop_times['departure_time'].str.slice(0,2).astype(int) >= 7]
stop_times = stop_times[stop_times['departure_time'].str.slice(0,2).astype(int) < 11]
stop_times

         trip_id  stop_id departure_time
71     2555_0196     1127       07:01:00
72     2555_0001     1127       07:06:30
73     2555_0001     1126       07:08:10
74     2555_0001     1125       07:10:10
75     2555_0001     1122       07:12:10
...          ...      ...            ...
10511  1910_0451     2017       10:47:50
10512  1910_0451     2019       10:49:40
10513  1910_0452     2019       10:55:00
10514  1910_0452     2117       10:57:10
10515  1910_0452     2116       10:58:40

[10018 rows x 3 columns]

In [34]:
stops_x = pd.read_table('Data/Tram/TBX/stops.txt', sep=',')[['stop_id','stop_name','stop_desc']]
stops_s = pd.read_table('Data/Tram/TBS/stops.txt', sep=',')[['stop_id','stop_name','stop_desc']]
stops = pd.concat([stops_x, stops_s])
stops = stops[~stops['stop_id'].str.startswith('S')]
stops['stop_id'] = stops['stop_id'].astype(int)
stops.drop_duplicates(subset=['stop_name'],keep='first', inplace=True)
stops['stop_desc'] = stops['stop_desc'].str[2:]
stops

    stop_id                  stop_name stop_desc
29     1032            Sant Feliu|C.C.      CCML
31     1031                Torreblanca      TRBL
33     1030                     Walden      WLDN
35     1029        Rambla de Sant Just      RBSJ
37     1028           Hospital SJD|TV3      HTV3
39     1016                    Montesa      MNTS
41     1015                 La Sardana      SRDN
43     1014           Pont d'Esplugues      PTSP
45     1213                  Can Clota      CLOT
47     1013              Ca n'Oliveres      OLIV
49     1012                  Can Rigal      RIGL
51     1011               Ernest Lluch      LLUC
53     1010           Avinguda de Xile      XILE
55     1009            Z.Universitària      UNIV
57     1008                Palau Reial      PLRL
59     1005                   Pius XII      PIUS
61     1004             Maria Cristina      MRCR
63     1003                   Numància      NMNC
65     1002                     L'Illa      ILLA
67     1001             Francesc Macià      FRMC
69     1017                   El Pedró      PDRO
71     1018            Ignasi Iglésias      IIGL
73     1019            Cornellà Centre      CNLL
75     1020                 Les Aigües      AIGU
77     1021            Fontsanta|Fatjó      FTJO
79     1022                 Bon Viatge      BVIA
81     1025               La Fontsanta      FSTA
83     1026  Centre Miquel Martí i Pol      CTMP
85     1127           Llevant-L.Planes      LLEV
15     2125   Sant Martí de Provençals      MRTI
16     2026                      Besòs      BSOS
18     2027         Alfons el Magnànim      ALFS
20     2028             Parc del Besòs      PARC
22     2013                La Catalana      CATA
24     2014         Sant Joan Baptista      JOAN
26     2016      Encants de Sant Adrià      NKNS
28     2017                   Sant Roc      SROC
30     2019                       Gorg      GORG
32     2111                    La Mina      MINA
34     2030           Estació St.Adrià      SABS
36     2029                 Port Fòrum      PORT
38     2010      Campus Diagonal-Besòs      CDBE
40     2009                      Fòrum      FRUM
42     2108                 El Maresme      MRSM

In [35]:
stops_w_times = stops.merge(stop_times, on='stop_id', how='left')
stops_w_times

      stop_id        stop_name stop_desc    trip_id departure_time
0        1032  Sant Feliu|C.C.      CCML  2555_0362       08:25:00
1        1032  Sant Feliu|C.C.      CCML  2555_0363       08:28:00
2        1032  Sant Feliu|C.C.      CCML  2555_0507       08:37:00
3        1032  Sant Feliu|C.C.      CCML  2555_0508       08:41:20
4        1032  Sant Feliu|C.C.      CCML  2555_0394       07:37:00
...       ...              ...       ...        ...            ...
5406     2108       El Maresme      MRSM  1910_0189       10:05:00
5407     2108       El Maresme      MRSM  1910_0190       10:24:30
5408     2108       El Maresme      MRSM  1910_0191       10:30:00
5409     2108       El Maresme      MRSM  1910_0192       10:48:30
5410     2108       El Maresme      MRSM  1910_0193       10:53:00

[5411 rows x 5 columns]

In [36]:
trips_x = pd.read_table('Data/Tram/TBX/trips.txt', sep=',')
trips_s = pd.read_table('Data/Tram/TBS/trips.txt', sep=',')
trips = pd.concat([trips_x, trips_s])
trips = trips[['route_id','trip_id']]

In [37]:
times_w_routes = stops_w_times.merge(trips, on='trip_id', how='left')
times_w_routes.drop_duplicates(subset=['stop_id','stop_name','route_id','departure_time'], keep='first', inplace=True)
times_w_routes['route_id'] = 'T' + times_w_routes['route_id'].astype(str)
times_w_routes

      stop_id        stop_name stop_desc    trip_id departure_time route_id
0        1032  Sant Feliu|C.C.      CCML  2555_0362       08:25:00       T3
1        1032  Sant Feliu|C.C.      CCML  2555_0363       08:28:00       T3
2        1032  Sant Feliu|C.C.      CCML  2555_0507       08:37:00       T3
3        1032  Sant Feliu|C.C.      CCML  2555_0508       08:41:20       T3
4        1032  Sant Feliu|C.C.      CCML  2555_0394       07:37:00       T3
...       ...              ...       ...        ...            ...      ...
5313     2108       El Maresme      MRSM  1908_0194       10:00:30       T4
5314     2108       El Maresme      MRSM  1908_0195       10:05:00       T4
5316     2108       El Maresme      MRSM  1908_0197       10:30:00       T4
5317     2108       El Maresme      MRSM  1908_0198       10:48:30       T4
5318     2108       El Maresme      MRSM  1908_0199       10:53:00       T4

[3272 rows x 6 columns]

In [38]:
times_w_routes['departure_time'] = pd.to_datetime(times_w_routes['departure_time'], format='%H:%M:%S')
times_w_routes = times_w_routes.sort_values(['stop_id', 'route_id', 'departure_time'])

times_w_routes['interval_minutes'] = (
    times_w_routes.groupby(['stop_id', 'route_id'])['departure_time']
    .diff()
    .dt.total_seconds()
    .div(60)
 )
avg_wait_times = (
    times_w_routes.dropna(subset=['interval_minutes'])
    .assign(wait_time=lambda df: df['interval_minutes'] / 2)
    .groupby(['stop_id', 'route_id', 'stop_name', 'stop_desc'], as_index=False)['wait_time']
    .mean()
 )
avg_wait_times = avg_wait_times[['stop_desc', 'route_id', 'wait_time']]
avg_wait_times['id'] = 'T' + '-' + avg_wait_times['route_id'] + '-' + avg_wait_times['stop_desc']
avg_wait_times = avg_wait_times[['id', 'wait_time']]
avg_wait_times

           id  wait_time
0   T-T1-FRMC   4.620000
1   T-T2-FRMC   3.189189
2   T-T3-FRMC   2.250000
3   T-T1-ILLA   5.090909
4   T-T2-ILLA   2.878049
..        ...        ...
79  T-T4-SABS   1.400602
80  T-T4-MRSM   1.375000
81  T-T6-MINA   6.544118
82  T-T5-MRTI   2.091518
83  T-T6-MRTI   3.267677

[84 rows x 2 columns]

In [39]:
exchange_edges_tram = exchange_edges_tram.merge(avg_wait_times, left_on='dest', right_on='id', how='left')
exchange_edges_tram = exchange_edges_tram[['origen', 'dest', 'tram', 'mode','lines','type','time',
                                           'wait_time','directed','geometry']]

exchange_edges_tram

,origen,dest,tram,mode,lines,type,time,wait_time,directed,geometry
0,ST-FRMC,T-T1-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,IU Stop - T1,Exchange - Self,02:00,4.620000,True,POINT (2.143174886703491 41.3922004699707)
1,T-T2-FRMC,T-T1-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,T2 - T1,Exchange - Self,01:00,4.620000,True,POINT (2.143174886703491 41.3922004699707)
2,T-T3-FRMC,T-T1-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,T3 - T1,Exchange - Self,01:00,4.620000,True,POINT (2.143174886703491 41.3922004699707)
3,ST-FRMC,T-T2-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,IU Stop - T2,Exchange - Self,02:00,3.189189,True,POINT (2.143174886703491 41.3922004699707)
4,T-T1-FRMC,T-T2-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,T1 - T2,Exchange - Self,01:00,3.189189,True,POINT (2.143174886703491 41.3922004699707)
...,...,...,...,...,...,...,...,...,...,...
1762,B-V33-3596,T-T6-MINA,La Mina - Ponent - La Mina,Bus - Tram,V33 - T6,Exchange,04:34,6.544118,True,"LINESTRING (2.2172843 41.4188065, 2.2174015 41..."
1763,B-B23-105999,T-T6-MINA,Rambla de la Mina - La Mina,Bus - Tram,B23 - T6,Exchange,01:48,6.544118,True,"LINESTRING (2.2224278 41.4182191, 2.222341 41...."
1764,B-B23-106000,T-T6-MINA,CAP La Mina - La Mina,Bus - Tram,B23 - T6,Exchange,04:10,6.544118,True,"LINESTRING (2.2201838 41.4156256, 2.2204138 41..."
1765,T-T5-PARC,T-T6-MINA,Parc del Besòs - La Mina,Tram - Tram,T5 - T6,Exchange,04:51,6.544118,True,"LINESTRING (2.2171297 41.4191608, 2.2171685 41..."
1766,T-T6-PARC,T-T6-MINA,Parc del Besòs - La Mina,Tram - Tram,T6 - T6,Exchange,04:51,6.544118,True,"LINESTRING (2.2171297 41.4191608, 2.2171685 41..."

# Metro

In [ ]:
exchange_edges_metro = exchange_edges[exchange_edges['dest'].str.startswith('M')]
exchange_edges_metro

In [ ]:
stop_times = pd.read_table('Data/GTFS_TMB/stop_times.txt', sep=',')
stop_times = stop_times[stop_times['departure_time'].notna()]
#stop_times = stop_times[['departure_time','stop_id']]
stop_times

In [ ]:
stops = pd.read_table('Data/GTFS_TMB/stops.txt', sep=',')
stops

In [ ]:
stops[stops['stop_code'] == 216]