In [40]:
import pandas as pd
import geopandas as gpd
from shapely import wkt

In [49]:
bus = pd.read_csv('Nodes/Bus.csv')
fgc = pd.read_csv('Nodes/FGC.csv')
metro = pd.read_csv('Nodes/Metro.csv')
tram = pd.read_csv('Nodes/Tram.csv')

all_stops = pd.concat([ bus, fgc, metro, tram], ignore_index=True)
all_stops['geometry']= all_stops['geometry'].apply(wkt.loads)
all_stops = gpd.GeoDataFrame(all_stops, geometry='geometry', crs="EPSG:4326")

exchange_edges = pd.read_csv('Edges/Exchanges.csv')

In [50]:
exchange_edges[exchange_edges['dest'].str.startswith('T')]

,origen,dest,tram,mode,lines,type,time,directed,geometry,origin_stop_id,origin_stop_type,destination_stop_id,destination_stop_type
11832,ST-FRMC,T-T1-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,IU Stop - T1,Exchange - Self,02:00,True,POINT (2.143174886703491 41.3922004699707),NaN,NaN,NaN,NaN
11833,T-T2-FRMC,T-T1-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,T2 - T1,Exchange - Self,01:00,True,POINT (2.143174886703491 41.3922004699707),NaN,NaN,NaN,NaN
11834,T-T3-FRMC,T-T1-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,T3 - T1,Exchange - Self,01:00,True,POINT (2.143174886703491 41.3922004699707),NaN,NaN,NaN,NaN
11835,ST-FRMC,T-T2-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,IU Stop - T2,Exchange - Self,02:00,True,POINT (2.143174886703491 41.3922004699707),NaN,NaN,NaN,NaN
11836,T-T1-FRMC,T-T2-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,T1 - T2,Exchange - Self,01:00,True,POINT (2.143174886703491 41.3922004699707),NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11976,T-T6-ALFS,T-T5-ALFS,Alfons el Magnànim - Alfons el Magnànim,Tram - Tram,T6 - T5,Exchange - Self,01:00,True,POINT (2.213568925857544 41.41719055175781),NaN,NaN,NaN,NaN
11977,ST-ALFS,T-T6-ALFS,Alfons el Magnànim - Alfons el Magnànim,Tram - Tram,IU Stop - T6,Exchange - Self,02:00,True,POINT (2.213568925857544 41.41719055175781),NaN,NaN,NaN,NaN
11978,T-T5-ALFS,T-T6-ALFS,Alfons el Magnànim - Alfons el Magnànim,Tram - Tram,T5 - T6,Exchange - Self,01:00,True,POINT (2.213568925857544 41.41719055175781),NaN,NaN,NaN,NaN
11979,T-T6-PARC,T-T5-PARC,Parc del Besòs - Parc del Besòs,Tram - Tram,T6 - T5,Exchange - Self,01:00,True,POINT (2.217633008956909 41.419429779052734),NaN,NaN,NaN,NaN
11980,T-T5-PARC,T-T6-PARC,Parc del Besòs - Parc del Besòs,Tram - Tram,T5 - T6,Exchange - Self,01:00,True,POINT (2.217633008956909 41.419429779052734),NaN,NaN,NaN,NaN

In [51]:
exchange_edges = exchange_edges.merge(all_stops[['id','stop_id']], left_on='dest', right_on='id', how='left')
exchange_edges

,origen,dest,tram,mode,lines,type,time,directed,geometry,origin_stop_id,origin_stop_type,destination_stop_id,destination_stop_type,id,stop_id
0,SB-2,B-59-2,Av Icària - Àlaba - Av Icària - Àlaba,Bus - Bus,IU Stop - 59,Exchange - Self,01:00,True,POINT (2.198984998801282 41.393104003754864),NaN,NaN,NaN,NaN,B-59-2,2
1,B-H16-2,B-59-2,Av Icària - Àlaba - Av Icària - Àlaba,Bus - Bus,H16 - 59,Exchange - Self,01:00,True,POINT (2.198984998801282 41.393104003754864),NaN,NaN,NaN,NaN,B-59-2,2
2,B-V27-2,B-59-2,Av Icària - Àlaba - Av Icària - Àlaba,Bus - Bus,V27 - 59,Exchange - Self,01:00,True,POINT (2.198984998801282 41.393104003754864),NaN,NaN,NaN,NaN,B-59-2,2
3,SB-2,B-H16-2,Av Icària - Àlaba - Av Icària - Àlaba,Bus - Bus,IU Stop - H16,Exchange - Self,01:00,True,POINT (2.198984998801282 41.393104003754864),NaN,NaN,NaN,NaN,B-H16-2,2
4,B-59-2,B-H16-2,Av Icària - Àlaba - Av Icària - Àlaba,Bus - Bus,59 - H16,Exchange - Self,01:00,True,POINT (2.198984998801282 41.393104003754864),NaN,NaN,NaN,NaN,B-H16-2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11976,T-T6-ALFS,T-T5-ALFS,Alfons el Magnànim - Alfons el Magnànim,Tram - Tram,T6 - T5,Exchange - Self,01:00,True,POINT (2.213568925857544 41.41719055175781),NaN,NaN,NaN,NaN,T-T5-ALFS,ALFS
11977,ST-ALFS,T-T6-ALFS,Alfons el Magnànim - Alfons el Magnànim,Tram - Tram,IU Stop - T6,Exchange - Self,02:00,True,POINT (2.213568925857544 41.41719055175781),NaN,NaN,NaN,NaN,T-T6-ALFS,ALFS
11978,T-T5-ALFS,T-T6-ALFS,Alfons el Magnànim - Alfons el Magnànim,Tram - Tram,T5 - T6,Exchange - Self,01:00,True,POINT (2.213568925857544 41.41719055175781),NaN,NaN,NaN,NaN,T-T6-ALFS,ALFS
11979,T-T6-PARC,T-T5-PARC,Parc del Besòs - Parc del Besòs,Tram - Tram,T6 - T5,Exchange - Self,01:00,True,POINT (2.217633008956909 41.419429779052734),NaN,NaN,NaN,NaN,T-T5-PARC,PARC
11980,T-T5-PARC,T-T6-PARC,Parc del Besòs - Parc del Besòs,Tram - Tram,T5 - T6,Exchange - Self,01:00,True,POINT (2.217633008956909 41.419429779052734),NaN,NaN,NaN,NaN,T-T6-PARC,PARC

# Tram

In [52]:
exchange_edges_tram = exchange_edges[exchange_edges['dest'].str.startswith('T')]
exchange_edges_tram

,origen,dest,tram,mode,lines,type,time,directed,geometry,origin_stop_id,origin_stop_type,destination_stop_id,destination_stop_type,id,stop_id
11832,ST-FRMC,T-T1-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,IU Stop - T1,Exchange - Self,02:00,True,POINT (2.143174886703491 41.3922004699707),NaN,NaN,NaN,NaN,T-T1-FRMC,FRMC
11833,T-T2-FRMC,T-T1-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,T2 - T1,Exchange - Self,01:00,True,POINT (2.143174886703491 41.3922004699707),NaN,NaN,NaN,NaN,T-T1-FRMC,FRMC
11834,T-T3-FRMC,T-T1-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,T3 - T1,Exchange - Self,01:00,True,POINT (2.143174886703491 41.3922004699707),NaN,NaN,NaN,NaN,T-T1-FRMC,FRMC
11835,ST-FRMC,T-T2-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,IU Stop - T2,Exchange - Self,02:00,True,POINT (2.143174886703491 41.3922004699707),NaN,NaN,NaN,NaN,T-T2-FRMC,FRMC
11836,T-T1-FRMC,T-T2-FRMC,Francesc Macià - Francesc Macià,Tram - Tram,T1 - T2,Exchange - Self,01:00,True,POINT (2.143174886703491 41.3922004699707),NaN,NaN,NaN,NaN,T-T2-FRMC,FRMC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11976,T-T6-ALFS,T-T5-ALFS,Alfons el Magnànim - Alfons el Magnànim,Tram - Tram,T6 - T5,Exchange - Self,01:00,True,POINT (2.213568925857544 41.41719055175781),NaN,NaN,NaN,NaN,T-T5-ALFS,ALFS
11977,ST-ALFS,T-T6-ALFS,Alfons el Magnànim - Alfons el Magnànim,Tram - Tram,IU Stop - T6,Exchange - Self,02:00,True,POINT (2.213568925857544 41.41719055175781),NaN,NaN,NaN,NaN,T-T6-ALFS,ALFS
11978,T-T5-ALFS,T-T6-ALFS,Alfons el Magnànim - Alfons el Magnànim,Tram - Tram,T5 - T6,Exchange - Self,01:00,True,POINT (2.213568925857544 41.41719055175781),NaN,NaN,NaN,NaN,T-T6-ALFS,ALFS
11979,T-T6-PARC,T-T5-PARC,Parc del Besòs - Parc del Besòs,Tram - Tram,T6 - T5,Exchange - Self,01:00,True,POINT (2.217633008956909 41.419429779052734),NaN,NaN,NaN,NaN,T-T5-PARC,PARC
11980,T-T5-PARC,T-T6-PARC,Parc del Besòs - Parc del Besòs,Tram - Tram,T5 - T6,Exchange - Self,01:00,True,POINT (2.217633008956909 41.419429779052734),NaN,NaN,NaN,NaN,T-T6-PARC,PARC

## TBX

# Metro

In [22]:
exchange_edges_metro = exchange_edges[exchange_edges['dest'].str.startswith('M')]
exchange_edges_metro

,origen,dest,tram,mode,lines,type,time,directed,geometry,id,stop_id
4588,SB-216,M-L2-216,Padilla - Provença - Sagrada Família,Bus - Metro,IU Stop - L2,Exchange - Self,03:00,True,POINT (2.1762244094290444 41.40649654928444),M-L2-216,216
4589,B-19-216,M-L2-216,Padilla - Provença - Sagrada Família,Bus - Metro,19 - L2,Exchange - Self,00:00,True,POINT (2.1762244094290444 41.40649654928444),M-L2-216,216
4590,B-V21-216,M-L2-216,Padilla - Provença - Sagrada Família,Bus - Metro,V21 - L2,Exchange - Self,00:00,True,POINT (2.1762244094290444 41.40649654928444),M-L2-216,216
4591,SM-216,M-L2-216,Sagrada Família - Sagrada Família,Metro - Metro,IU Stop - L2,Exchange - Self,03:00,True,POINT (2.17449041 41.40441909),M-L2-216,216
4592,M-L5-216,M-L2-216,Sagrada Família - Sagrada Família,Metro - Metro,L5 - L2,Exchange - Self,02:00,True,POINT (2.17449041 41.40441909),M-L2-216,216
...,...,...,...,...,...,...,...,...,...,...,...
13771,B-V23-475,M-L5-531,Pg Maragall - Dante Alighieri - Horta,Bus - Metro,V23 - L5,Exchange,04:57,True,"LINESTRING (2.1629728 41.4285634, 2.162696 41....",M-L5-531,531
13772,SB-164,M-L5-533,Santa Rosalia - Besòs - El Coll | La Teixonera,Bus - Metro,IU Stop - L5,Exchange,02:53,True,"LINESTRING (2.1456907 41.4213788, 2.1459798 41...",M-L5-533,533
13773,B-19-164,M-L5-533,Santa Rosalia - Besòs - El Coll | La Teixonera,Bus - Metro,19 - L5,Exchange,02:53,True,"LINESTRING (2.1456907 41.4213788, 2.1459798 41...",M-L5-533,533
13774,B-119-164,M-L5-533,Santa Rosalia - Besòs - El Coll | La Teixonera,Bus - Metro,119 - L5,Exchange,02:53,True,"LINESTRING (2.1456907 41.4213788, 2.1459798 41...",M-L5-533,533
13775,B-H2-164,M-L5-533,Santa Rosalia - Besòs - El Coll | La Teixonera,Bus - Metro,H2 - L5,Exchange,02:53,True,"LINESTRING (2.1456907 41.4213788, 2.1459798 41...",M-L5-533,533

In [33]:
stop_times = pd.read_table('Data/GTFS_TMB/stop_times.txt', sep=',')
stop_times = stop_times[stop_times['departure_time'].notna()]
#stop_times = stop_times[['departure_time','stop_id']]
stop_times

/var/folders/95/s4thp5290fd41pw2cj8713k80000gn/T/ipykernel_8038/1487966060.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  stop_times = pd.read_table('Data/GTFS_TMB/stop_times.txt', sep=',')

,trip_id,arrival_time,departure_time,stop_id,stop_sequence
0,1.104.11029968,05:00:00,05:00:00,1.932,1
1,1.104.11029968,05:02:07,05:02:07,1.93,2
2,1.104.11029969,05:04:27,05:04:27,1.93,1
3,1.104.11029969,05:07:05,05:07:41,1.932,2
4,1.104.11029969,05:09:45,05:10:10,1.933,3
...,...,...,...,...,...
1828503,2.978.127.3379936.4099,23:14:00,23:14:00,2.2984.695617,2
1828504,2.978.127.3379936.4099,23:16:00,23:16:00,2.778.693751,3
1828509,2.978.127.3379936.4099,23:26:00,23:26:00,2.2532.689812,8
1828510,2.978.127.3379937.4099,23:26:00,23:26:00,2.2532.689812,1
1828513,2.978.127.3379937.4099,23:44:00,23:44:00,2.3286.697341,4

In [30]:
stops = pd.read_table('Data/GTFS_TMB/stops.txt', sep=',')
stops

,stop_id,stop_code,stop_name,stop_lat,stop_lon,stop_url,location_type,parent_station,wheelchair_boarding
0,1.111,111,Hospital de Bellvitge,41.344677,2.107242,NaN,0,P.6660111,1.0
1,E.1011101,11101,Ascensor - Residència sanitària,41.344324,2.106855,NaN,2,P.6660111,1.0
2,E.11101,11101,Residència sanitària,41.344357,2.106669,NaN,2,P.6660111,2.0
3,P.6660111,6660111,Hospital de Bellvitge,41.344677,2.107242,NaN,1,NaN,NaN
4,1.112,112,Bellvitge,41.350975,2.110917,NaN,0,P.6660112,1.0
...,...,...,...,...,...,...,...,...,...
3465,2.9979.699905,9979,"Meridiana, 298",41.422661,2.187097,NaN,0,NaN,0.0
3466,2.9980.699903,9980,"Meridiana, 320",41.424803,2.186799,NaN,0,NaN,0.0
3467,2.9981.699910,9981,"Concepción Arenal, 103-105",41.423852,2.183991,NaN,0,NaN,0.0
3468,2.9994.700010,9994,"Torrent de la Perera, 23",41.454924,2.191757,NaN,0,NaN,0.0
3469,2.9999.700155,9999,"Madrazo, 104",41.396888,2.144511,NaN,0,NaN,0.0

In [34]:
stops[stops['stop_code'] == 216]

,stop_id,stop_code,stop_name,stop_lat,stop_lon,stop_url,location_type,parent_station,wheelchair_boarding
236,1.216,216,Sagrada Família,41.403985,2.175106,NaN,0,P.6660216,1.0
955,2.216.699736,216,Padilla - Provença,41.406497,2.176224,NaN,0,NaN,1.0